### ISSUE TITLE
[Bug]: Server: panic: struct binding failed: Unprocessable Entity

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#146]
### What happened?

Go Fiber throwing 422 unprocessable entity status code during httptest for API testing

```go
// controller_test.go
func TestHandleJwtSignUp(t *testing.T) {
	app := fiber.New()

	app.Post("/api/v1/login/jwt", auth.HandleJwtSignUp)
	// create a post body with struct
	body := MockUser{
		Firstname: "Jake",
		Lastname:  "Sung",
		Email:     "nellow1102@gmail.com",
		Username:  "developerasun",
	}

	// struct needs to be encoded with buffer
	var buf bytes.Buffer
	err := json.NewEncoder(&buf).Encode(body)

	if err != nil {
		log.Fatal(err)
	}

	req := httptest.NewRequest(http.MethodPost, "/api/v1/login/jwt", &buf)

	response, _ := app.Test(req)
	fmt.Println(req)
	fmt.Println(response.StatusCode)
}

// controller.go 
func HandleJwtSignUp(c *fiber.Ctx) error {
	log.Printf("client sent: %s", string(c.Request().Body()))
	allParams := c.AllParams()

	color.Blue("params from client: ", allParams)

	user := new(database.User)

	if err := c.BodyParser(&user); err != nil {
		log.Panicf("struct binding failed: %s", err.Error())
		return c.SendStatus(fiber.StatusInternalServerError)
	}

	db := database.Conn
	result := db.Create(&user)

	status := useErrorCallback(c, result.Error, "post")

	return c.SendStatus(status)
}

```

### Relevant log output

```shell
go test
2022/10/18 22:39:44 client sent: {"firstname":"Jake","lastname":"Sung","email":"nellow1102@gmail.com","username":"developerasun"}
params from client: 
%!(EXTRA map[string]string=map[])2022/10/18 22:39:44 struct binding failed: Unprocessable Entity
panic: struct binding failed: Unprocessable Entity

goroutine 20 [running]:
log.Panicf({0xf7ad58?, 0x14?}, {0xc00008fb78?, 0xc00008fb68?, 0x1?})
        C:/Program Files/Go/src/log/log.go:395 +0x67
github.com/asunlabs/pawcon-monorepo/server/src/feature/auth.HandleJwtSignUp(0xc0002dc000)
        D:/github/pawcon-monorepo/apps/server/src/feature/auth/controller.go:64 +0x155
github.com/gofiber/fiber/v2.(*App).next(0xc0002c2a00, 0xc0002dc000)
        C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/router.go:132 +0x1c2
github.com/gofiber/fiber/v2.(*App).handler(0xc0002c2a00, 0x87bad7?)
        C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/router.go:159 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc000103440, {0x105f950?, 0xc0002b6410})
        C:/Users/nello/go/pkg/mod/github.com/valyala/fasthttp@v1.39.0/server.go:2305 +0x1248
github.com/valyala/fasthttp.(*Server).ServeConn(0xc000103440, {0x105f950?, 0xc0002b6410?})
        C:/Users/nello/go/pkg/mod/github.com/valyala/fasthttp@v1.39.0/server.go:1978 +0x8d
github.com/gofiber/fiber/v2.(*App).Test.func1()
        C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/app.go:888 +0x88
created by github.com/gofiber/fiber/v2.(*App).Test
        C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/app.go:880 +0x430
exit status 2
```

**Comment by developerasun** [comment]
## solution

**code blocks problematic**

```go
// controller.go
	if err := c.BodyParser(&user); err != nil {
		log.Panicf("struct binding failed: %s", err.Error())
		return c.SendStatus(fiber.StatusInternalServerError)
	}
```

> BodyParser binds the request body to a struct. It supports decoding the following content types based on the Content-Type header: application/json, application/xml, application/x-www-form-urlencoded, multipart/form-data If none of the content types above are matched, it will return a ErrUnprocessableEntity error
