### ISSUE TITLE
[Bug]: GORM panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#147]
### What happened?

GORM create op failing in httptest

### Relevant log output

```shell
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x938762]

goroutine 7 [running]:
gorm.io/gorm.(*DB).Create(0xc000324000?, {0xb19d00?, 0xc0002eb4a0?})
	C:/Users/nello/go/pkg/mod/gorm.io/gorm@v1.23.8/finisher_api.go:18 +0x22
github.com/asunlabs/pawcon-monorepo/server/src/feature/auth.HandleJwtSignUp(0xc000324000)
	d:/github/pawcon-monorepo/apps/server/src/feature/auth/controller.go:67 +0x119
github.com/gofiber/fiber/v2.(*App).next(0xc000309180, 0xc000324000)
	C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/router.go:132 +0x1c2
github.com/gofiber/fiber/v2.(*App).handler(0xc000309180, 0x4dbad7?)
	C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/router.go:159 +0x45
github.com/valyala/fasthttp.(*Server).serveConn(0xc000149680, {0xcbf190?, 0xc0002fc500})
	C:/Users/nello/go/pkg/mod/github.com/valyala/fasthttp@v1.39.0/server.go:2305 +0x1248
github.com/valyala/fasthttp.(*Server).ServeConn(0xc000149680, {0xcbf190?, 0xc0002fc500?})
	C:/Users/nello/go/pkg/mod/github.com/valyala/fasthttp@v1.39.0/server.go:1978 +0x8d
github.com/gofiber/fiber/v2.(*App).Test.func1()
	C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/app.go:888 +0x88
created by github.com/gofiber/fiber/v2.(*App).Test
	C:/Users/nello/go/pkg/mod/github.com/gofiber/fiber/v2@v2.37.0/app.go:880 +0x430
FAIL	github.com/asunlabs/pawcon-monorepo/server/src/feature/auth	0.122s
FAIL
```

**Comment by developerasun** [comment]
## Solution: connect database and automigate models used in the httptest. 

```go
// Wrong
	app := fiber.New()
	app.Post("/auth/signup", auth.HandleJwtSignUp)

       // ... codes
      	req := httptest.NewRequest(http.MethodPost, "/auth/signup", &buf)
	req.Header.Set("Content-Type", "application/json")

	resp, _ := app.Test(req)
```

```go
        app := fiber.New()
       	database.Connect(database.ReturnAllModel())
	app.Post("/auth/signup", auth.HandleJwtSignUp)
       
       // ... codes
      	req := httptest.NewRequest(http.MethodPost, "/auth/signup", &buf)
	req.Header.Set("Content-Type", "application/json")

	resp, _ := app.Test(req)


```

**Comment by developerasun** [comment]
## Reference 

> This occurs when a variable is nil. in query := db.First(&m, vars["id"])

> I suspect that db is nil. I do not see where you are creating it. You need to do something like:

- https://stackoverflow.com/questions/31467498/why-does-gorm-db-first-panic-with-invalid-memory-address-or-nil-pointer-deref
