### ISSUE TITLE
[Bug]: ERC777: token recipient contract has no implementer for ERC777TokensRecipient

### ISSUE THREAD

**Issue by developerasun** [asunlabs/pawcon-monorepo#35]
### What happened?

UpgradeableERC777 stake function reverts with below reason string

```
Error: VM Exception while processing transaction: reverted with reason string 'ERC777: token recipient contract has no implementer for ERC777TokensRecipient'
```

### Relevant log output

```shell
Error: VM Exception while processing transaction: reverted with reason string 'ERC777: token recipient contract has no implementer for ERC777TokensRecipient'
    at UP_CatnipVer02.onlyProxy (@openzeppelin/contracts-upgradeable/proxy/utils/UUPSUpgradeable.sol:39)
    at UP_CatnipVer02._callTokensReceived (@openzeppelin/contracts-upgradeable/token/ERC777/ERC777Upgradeable.sol:497)
    at UP_CatnipVer02._send (@openzeppelin/contracts-upgradeable/token/ERC777/ERC777Upgradeable.sol:389)
    at UP_CatnipVer02.operatorSend (@openzeppelin/contracts-upgradeable/token/ERC777/ERC777Upgradeable.sol:229)
    at <UnrecognizedContract>.<unknown> (0x0ed64d01d0b4b655e410ef1441dd677b695639e7)
    at UP_CatnipVer02.stake (contracts/token/upgradeable/token/ERC777/UP_Catnip/UP_CatnipVer02.sol:56)    at <UnrecognizedContract>.<unknown> (0x0ed64d01d0b4b655e410ef1441dd677b695639e7)
    at async HardhatNode._mineBlockWithPendingTxs (D:\github\pawcon-monorepo\node_modules\.pnpm\hardhat@2.9.9_mu66ohdiwyrigyorzidgf4bsdu\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:1773:23)
    at async HardhatNode.mineBlock (D:\github\pawcon-monorepo\node_modules\.pnpm\hardhat@2.9.9_mu66ohdiwyrigyorzidgf4bsdu\node_modules\hardhat\src\internal\hardhat-network\provider\node.ts:466:16)        
    at async EthModule._sendTransactionAndReturnHash (D:\github\pawcon-monorepo\node_modules\.pnpm\hardhat@2.9.9_mu66ohdiwyrigyorzidgf4bsdu\node_modules\hardhat\src\internal\hardhat-network\provider\modules\eth.ts:1504:18)
    at async HardhatNetworkProvider.request (D:\github\pawcon-monorepo\node_modules\.pnpm\hardhat@2.9.9_mu66ohdiwyrigyorzidgf4bsdu\node_modules\hardhat\src\internal\hardhat-network\provider\provider.ts:118:18)
    at async EthersProviderWrapper.send (D:\github\pawcon-monorepo\node_modules\.pnpm\@nomiclabs+hardhat-ethers@2.0.6_ethers@5.6.9+hardhat@2.9.9\node_modules\@nomiclabs\hardhat-ethers\src\internal\ethers-provider-wrapper.ts:13:20)
```

**Comment by developerasun** [comment]
## Solution

Implement ERC777Recipient, ERC777Sender, ERC1820Registry.
